"""Initial table

Revision ID: 4d15e2da3d11
Revises: cb77dfe54211
Create Date: 2021-09-29 17:32:45.422751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d15e2da3d11'
down_revision = 'cb77dfe54211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content',
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('cover_image', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('displayed', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('recommended_by_name', sa.String(), nullable=True),
    sa.Column('recommended_by_age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('content_id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('content')
    # ### end Alembic commands ###
