"""Added new columns to Content table

Revision ID: 622680a3a2be
Revises: 
Create Date: 2021-09-26 14:02:46.122987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '622680a3a2be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Content', sa.Column('reason', sa.String(), nullable=True))
    op.add_column('Content', sa.Column('recommended_by_name', sa.String(), nullable=True))
    op.add_column('Content', sa.Column('recommended_by_age', sa.Integer(), nullable=True))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content', 'reason', 'recommended_by_name', 'recommended_by_age')
    # ### end Alembic commands ###
